[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

# Proxy API requests to avoid CORS issues
[[redirects]]
  from = "/api/*"
  to = "https://scrum-poker-9c6i.onrender.com/api/:splat"
  status = 200
  force = true

# Proxy WebSocket connections (Socket.io)
[[redirects]]
  from = "/socket.io/*"
  to = "https://scrum-poker-9c6i.onrender.com/socket.io/:splat"
  status = 200
  force = true

# Redirect all routes to index.html for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable" 